### ISSUE TITLE
DH Param

### ISSUE THREAD

**Issue by ericrange** [ThreatLabsNL/TLScan#10]
Hi :)

is it possible to get the dh param for the DH ciphers?
actually just the key length would be enough.

and if a curve is used, to display this curve?

**Comment by mjol** [comment]
Hi Eric,

I'll have a think about that... :) It will require analyses of other handshake messages.

**Comment by mjol** [comment]
I added the encryption bits for most ciphers. Working on a solution for the RSA and DH params, from there curves should be relatively easy

**Comment by ericrange** [comment]
:D <3 👍

**Comment by ericrange** [comment]
any updates? :)

**Comment by mjol** [comment]
Implemented
