### ISSUE TITLE
Some hosts do not respond correctly

### ISSUE THREAD

**Issue by ericrange** [ThreatLabsNL/TLScan#12]
hey im not sure why this occurs. but some hosts like "www.radarlux.com:443" do not respond properly.
do you know why?

**Comment by mjol** [comment]
Hi Eric, 

It is not clear to me what you meant with "do not respond properly". Quickly looking at the example you gave it seems as there is no service on port 443, which means there is 'no' response at all.

**Comment by ericrange** [comment]
ok. im an idiot. srry :D
