### ISSUE TITLE
SSLv2 do not work

### ISSUE THREAD

**Issue by ericrange** [ThreatLabsNL/TLScan#5]
if i scan sslv2 servers, there is no output that sslv2 is enabled?

**Comment by ericrange** [comment]
do you know why? can u give me an hint? so that i can fix that?

**Comment by mjol** [comment]
Hi Eric,

Well, this is definitely a bug. I will have a look and see why it is not detecting SSLv2.

**Comment by mjol** [comment]
There was an issue with the SSLv2 record as well as a missing function, which I have added. SSLv2 should now work fine.
