### ISSUE TITLE
SSLv2 still does not work

### ISSUE THREAD

**Issue by ericrange** [ThreatLabsNL/TLScan#6]
I just took an example site from ssllabs.com: ottservice.aviion.tv
ssllabs told me that this site is using sslv2:
![image](https://cloud.githubusercontent.com/assets/1785416/20795578/2ccd39fa-b7d2-11e6-851e-4733b2af9120.png)

but the script did not notice that.
![image](https://cloud.githubusercontent.com/assets/1785416/20795555/0a757f0c-b7d2-11e6-873a-ea6f168e558a.png)

**Comment by mjol** [comment]
Hi Eric,

I have tried the target you suggest and the it seems to be able to detect SSLv2 on the host you mention.
<img width="531" alt="screen shot 2016-12-01 at 14 57 42" src="https://cloud.githubusercontent.com/assets/12637923/20796477/929b9c5a-b7d6-11e6-8af0-2f894524bde4.png">

Do you have the latest version?

**Comment by ericrange** [comment]
mmh yes :(
which python version do you use?
mine is 2.7.12

**Comment by ericrange** [comment]
ok when i execute the script on a linux machine, it works :O
on windows, it doesnt seem to work. maybe its blocked by the firewall... or something else.
