### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by ericrange** [ThreatLabsNL/TLScan#7]
So, i want to say, that this script is just unbelievable :D
never saw such skills for a long time :)

i use it, to check my own server for poodle, drown, etc...
but i use python 3.

Is there an easy way to transform the script for python 3?

```
============================================
TLScan
============================================
[[32mi[0m] No port specified, setting a default one (443)
[[32mi[0m] Processing target: mdm.jenoptik.com on port:  443...
===============- [34;1mProtocols[0m -================
[+] Supported encryption protocols:
Traceback (most recent call last):
  File "main.py", line 860, in <module>
    main()
  File "main.py", line 839, in main
    processTarget(target)
  File "main.py", line 784, in processTarget
    protocols = enumProtocols()
  File "main.py", line 701, in enumProtocols
    response = tls.doClientHello(p) # then send hello
  File "main.py", line 504, in doClientHello
    helloMsg = self.tlsHello(protocol, cipher)
  File "main.py", line 466, in tlsHello
    record += struct.pack("!H", hp_len)
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by mjol** [comment]
Thanks you, good to hear you like it! :)
I will look at refactoring for python 3. May take some time though.
I haven't tested it on windows... I notice the CLI colors are also not working on your windows terminal...

**Comment by ericrange** [comment]
if there is anything i can do, just tell me ;)

**Comment by mjol** [comment]
Eric, 
I just pushed a refactored (rewrite) to support python3 (starting at v3.4) and be more modular. I will port other functionality, but that will take some more time.
