### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by ericrange** [ThreatLabsNL/TLScan#8]
Hey,

the python 3 implementation is just wonderful :D
but i get an error
```
Traceback (most recent call last):
  File "main.py", line 1068, in <module>
    test(t)
  File "main.py", line 1058, in test
    supported_protocols = enum.get_version_support(versions)
  File "main.py", line 986, in get_version_support
    response = tls.send_record(self.get_ecc_extended_client_hello(TLS.versions[v], TLS.ciphers_tls))
  File "main.py", line 922, in send_record
    rec = Record(TLS.get_version_from_bytes(header[1:3]), struct.unpack('!B', header[0:1])[0])
  File "main.py", line 908, in get_version_from_bytes
    if TLS.is_ssl3_tls((version_bytes[0], version_bytes[1])) or TLS.is_ssl2((version_bytes[0], version_bytes[1])):
IndexError: index out of range
```

do you know why this happens?

**Comment by mjol** [comment]
Yes, I know... :( it is because no validation is done on whether or not the header (obtained on line 921) is actually received. I will push a fix soon (also contains some others) but in the meantime you could overcome it by adding a line that checks the header is received (e.g. "if header:")

**Comment by mjol** [comment]
Should be resolved for most instances, however validation could be more strict.
